import { $ } from "https://esm.sh/rubymonkey@1.2.0"

const data = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`

const day7 = data => {
  const manifold = data.trim().split("\n").map($`chars`)
  const s = manifold.first.indexOf("S")
  let indices = [s]
  const counts = {[s]: 1}
  manifold.each(row => {
    const splitters = row.filter_map((x,i) => x == "^" ? i : null)
    splitters.each(n => {
      const value = counts[n];
      counts[n - 1] = (counts[n - 1] ?? 0) + value;
      counts[n + 1] = (counts[n + 1] ?? 0) + value;
      counts[n] = 0;
    })
    indices = indices.map(n => splitters.includes(n) ? [n-1,n+1] : n).flatten.uniq
  })
  return counts.values.sum
}

console.log(day7(data))
